//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    public Category()
    {
        this.Products = new HashSet<Product>();
    }

    public int Category_ID { get; set; }
    public string Category_Name { get; set; }
    public string Description { get; set; }
    public byte[] Picture { get; set; }

    public virtual ICollection<Product> Products { get; set; }
}

public partial class Customer
{
    public Customer()
    {
        this.Orders = new HashSet<Order>();
    }

    public string Customer_ID { get; set; }
    public string Company_Name { get; set; }
    public string Contact_Name { get; set; }
    public string Contact_Title { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string Postal_Code { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Employee
{
    public Employee()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Employee_ID { get; set; }
    public string Last_Name { get; set; }
    public string First_Name { get; set; }
    public string Title { get; set; }
    public Nullable<System.DateTime> Birth_Date { get; set; }
    public Nullable<System.DateTime> Hire_Date { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string Postal_Code { get; set; }
    public string Country { get; set; }
    public string Home_Phone { get; set; }
    public string Extension { get; set; }
    public byte[] Photo { get; set; }
    public string Notes { get; set; }
    public Nullable<int> Reports_To { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Order
{
    public Order()
    {
        this.Order_Details = new HashSet<Order_Detail>();
    }

    public int Order_ID { get; set; }
    public string Customer_ID { get; set; }
    public Nullable<int> Employee_ID { get; set; }
    public string Ship_Name { get; set; }
    public string Ship_Address { get; set; }
    public string Ship_City { get; set; }
    public string Ship_Region { get; set; }
    public string Ship_Postal_Code { get; set; }
    public string Ship_Country { get; set; }
    public Nullable<int> Ship_Via { get; set; }
    public Nullable<System.DateTime> Order_Date { get; set; }
    public Nullable<System.DateTime> Required_Date { get; set; }
    public Nullable<System.DateTime> Shipped_Date { get; set; }
    public Nullable<decimal> Freight { get; set; }

    public virtual Customer Customer { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual ICollection<Order_Detail> Order_Details { get; set; }
    public virtual Shipper Shipper { get; set; }
}

public partial class Order_Detail
{
    public int Order_ID { get; set; }
    public int Product_ID { get; set; }
    public decimal Unit_Price { get; set; }
    public short Quantity { get; set; }
    public float Discount { get; set; }

    public virtual Product Product { get; set; }
    public virtual Order Order { get; set; }
}

public partial class Product
{
    public Product()
    {
        this.Order_Details = new HashSet<Order_Detail>();
    }

    public int Product_ID { get; set; }
    public Nullable<int> Supplier_ID { get; set; }
    public Nullable<int> Category_ID { get; set; }
    public string Product_Name { get; set; }
    public string English_Name { get; set; }
    public string Quantity_Per_Unit { get; set; }
    public Nullable<decimal> Unit_Price { get; set; }
    public Nullable<short> Units_In_Stock { get; set; }
    public Nullable<short> Units_On_Order { get; set; }
    public Nullable<short> Reorder_Level { get; set; }
    public bool Discontinued { get; set; }

    public virtual Category Category { get; set; }
    public virtual ICollection<Order_Detail> Order_Details { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class Shipper
{
    public Shipper()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Shipper_ID { get; set; }
    public string Company_Name { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Supplier
{
    public Supplier()
    {
        this.Products = new HashSet<Product>();
    }

    public int Supplier_ID { get; set; }
    public string Company_Name { get; set; }
    public string Contact_Name { get; set; }
    public string Contact_Title { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string Postal_Code { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }

    public virtual ICollection<Product> Products { get; set; }
}
